### ISSUE TITLE
Error with coberture report during the build

### ISSUE THREAD

**Issue by C4tWithShell** [elegoff/sonar-rust#71]
I tried to build the plugin but I faced issues with cobertura report - The file name 'src/process/child.rs' of the coverage report can not be resolved, the file does not exist in all <source>.

Here is logs from build
```
ests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.005 sec <<< FAILURE! - in org.elegoff.plugins.communityrust.coverage.cobertura.StaxParserTest
test_grammars(org.elegoff.plugins.communityrust.coverage.cobertura.StaxParserTest)  Time elapsed: 0.004 sec  <<< ERROR!
java.lang.IllegalArgumentException: Null InputStream is not a valid argument
        at org.elegoff.plugins.communityrust.coverage.cobertura.StaxParserTest.test_grammar_parsable(StaxParserTest.java:47)
        at org.elegoff.plugins.communityrust.coverage.cobertura.StaxParserTest.test_grammars(StaxParserTest.java:52)

Running org.elegoff.plugins.communityrust.coverage.cobertura.CoberturaSensorTest
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/wrong_eof.xml'
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/cobertura.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/coverage-other.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
ERROR The file name 'src/process/child.rs' of the coverage report can not be resolved, the file does not exist in all <source>.
ERROR 3 file paths can not be resolved, coverage measures will be ignored for those files
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/coverage-other-2.xml'
ERROR Ambigous file name 'test.rs' detected in mulitple location of the coverage report <source>.
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/cobertura.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/invalid.xml'
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/cobertura.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/coverage-other-2.xml'
ERROR Ambigous file name 'test.rs' detected in mulitple location of the coverage report <source>.
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/cobertura.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/unresolved.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
ERROR The file name '/mymodule/src/fake.rs' of the coverage report can not be resolved, the file does not exist in all <source>.
ERROR 2 file paths can not be resolved, coverage measures will be ignored for those files
WARN  No report was found for community.rust.cobertura.reportPaths using pattern /report/not/found.xml
INFO  Rust cobertura coverage
INFO  Importing report '/tmp/junit7353939638428175178/sonar-rust/unresolved.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
ERROR The file name '/mymodule/src/fake.rs' of the coverage report can not be resolved, the file does not exist in all <source>.
ERROR 2 file paths can not be resolved, coverage measures will be ignored for those files
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/empty.xml'
WARN  Ignoring report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/empty.xml' which seems to be empty. 'org.elegoff.plugins.communityrust.coverage.cobertura.CoberturaException'
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.155 sec - in org.elegoff.plugins.communityrust.coverage.cobertura.CoberturaSensorTest
Running org.elegoff.plugins.communityrust.rules.RustRulesDefinitionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.037 sec - in org.elegoff.plugins.communityrust.rules.RustRulesDefinitionTest
Running org.elegoff.plugins.communityrust.CommunityRustPluginTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.012 sec - in org.elegoff.plugins.communityrust.CommunityRustPluginTest
Running org.elegoff.plugins.communityrust.RustSensorTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.32 sec - in org.elegoff.plugins.communityrust.RustSensorTest

Results :

Tests in error: 
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  FileAdjustorTest.setup:45 » IllegalState Unable to resolve module baseDir
  StaxParserTest.test_grammars:52->test_grammar_parsable:47 » IllegalArgument Nu...

Tests run: 78, Failures: 0, Errors: 12, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Community Rust SonarQube plugin 0.2.2-SNAPSHOT:
[INFO] 
[INFO] Community Rust SonarQube plugin .................... SUCCESS [  0.202 s]
[INFO] Community Rust :: Frontend ......................... SUCCESS [  5.570 s]
[INFO] Community Rust :: Checks ........................... SUCCESS [  1.169 s]
[INFO] Rust language analyzer ............................. FAILURE [ 15.976 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time:  23.247 s
[INFO] Finished at: 2023-10-05T21:32:00+03:00
[INFO] ------------------------------------------------------------------------
[ERROR] Failed to execute goal org.apache.maven.plugins:maven-surefire-plugin:2.19.1:test (default-test) on project community-rust-plugin: There are test failures.
[ERROR] 
[ERROR] Please refer to /home/vshell/sonar-rust/community-rust-plugin/target/surefire-reports for the individual test results.
[ERROR] -> [Help 1]
[ERROR] 
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR] 
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/MojoFailureException
[ERROR] 
[ERROR] After correcting the problems, you can resume the build with the command
[ERROR]   mvn <args> -rf :community-rust-plugin
```

**Comment by elegoff** [comment]
Thanks for this. That is a typical "it works on my machine" syndrom since there was a missing empty folder in the git tracking.
However that only explains 11 out of the 12 errors you are reporting (FileAdjustorTest unit test)
The remainer error you get on StaxParserTest is still unexplained. Do you still facing when using the very recent version of the master branch ?

**Comment by C4tWithShell** [comment]
Yes, I am still facing it
```
Running org.elegoff.plugins.communityrust.coverage.cobertura.StaxParserTest
Tests run: 2, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 0.007 sec <<< FAILURE! - in org.elegoff.plugins.communityrust.coverage.cobertura.StaxParserTest
test_grammars(org.elegoff.plugins.communityrust.coverage.cobertura.StaxParserTest)  Time elapsed: 0.006 sec  <<< ERROR!
java.lang.IllegalArgumentException: Null InputStream is not a valid argument
	at org.elegoff.plugins.communityrust.coverage.cobertura.StaxParserTest.test_grammar_parsable(StaxParserTest.java:47)
	at org.elegoff.plugins.communityrust.coverage.cobertura.StaxParserTest.test_grammars(StaxParserTest.java:52)

Running org.elegoff.plugins.communityrust.coverage.cobertura.CoberturaSensorTest
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/wrong_eof.xml'
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/cobertura.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/coverage-other.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
ERROR The file name 'src/process/child.rs' of the coverage report can not be resolved, the file does not exist in all <source>.
ERROR 3 file paths can not be resolved, coverage measures will be ignored for those files
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/coverage-other-2.xml'
ERROR Ambigous file name 'test.rs' detected in mulitple location of the coverage report <source>.
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/cobertura.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/invalid.xml'
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/cobertura.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/coverage-other-2.xml'
ERROR Ambigous file name 'test.rs' detected in mulitple location of the coverage report <source>.
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/cobertura.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/unresolved.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
ERROR The file name '/mymodule/src/fake.rs' of the coverage report can not be resolved, the file does not exist in all <source>.
ERROR 2 file paths can not be resolved, coverage measures will be ignored for those files
WARN  No report was found for community.rust.cobertura.reportPaths using pattern /report/not/found.xml
INFO  Rust cobertura coverage
INFO  Importing report '/tmp/junit3302861841520628640/sonar-rust/unresolved.xml'
WARN  Invalid directory path src/test/resources/org/elegoff/plugins/rust/cobertura found in 'source' element
ERROR The file name '/mymodule/src/fake.rs' of the coverage report can not be resolved, the file does not exist in all <source>.
ERROR 2 file paths can not be resolved, coverage measures will be ignored for those files
INFO  Rust cobertura coverage
INFO  Importing report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/empty.xml'
WARN  Ignoring report '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/empty.xml' which seems to be empty. 'org.elegoff.plugins.communityrust.coverage.cobertura.CoberturaException'
Tests run: 12, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.091 sec - in org.elegoff.plugins.communityrust.coverage.cobertura.CoberturaSensorTest
Running org.elegoff.plugins.communityrust.rules.RustRulesDefinitionTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.025 sec - in org.elegoff.plugins.communityrust.rules.RustRulesDefinitionTest
Running org.elegoff.plugins.communityrust.CommunityRustPluginTest
Tests run: 1, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.016 sec - in org.elegoff.plugins.communityrust.CommunityRustPluginTest
Running org.elegoff.plugins.communityrust.RustSensorTest
Tests run: 6, Failures: 0, Errors: 0, Skipped: 0, Time elapsed: 0.212 sec - in org.elegoff.plugins.communityrust.RustSensorTest

Results :

Tests in error: 
  StaxParserTest.test_grammars:52->test_grammar_parsable:47 » IllegalArgument Nu...

Tests run: 78, Failures: 0, Errors: 1, Skipped: 0

[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary for Community Rust SonarQube plugin 0.2.2-SNAPSHOT:
[INFO] 
[INFO] Community Rust SonarQube plugin .................... SUCCESS [  0.443 s]
[INFO] Community Rust :: Frontend ......................... SUCCESS [  6.520 s]
[INFO] Community Rust :: Checks ........................... SUCCESS [  1.091 s]
[INFO] Rust language analyzer ............................. FAILURE [ 17.865 s]
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
```

**Comment by C4tWithShell** [comment]
Yes, I have it
 `home/vshell/sonar-rust/community-rust-plugin/src/test/resources/org/elegoff/plugins/communityrust/cobertura/dtd-test.xml `
```
<?xml version="1.0"?>
<!DOCTYPE test SYSTEM "http://com.foo.bar/fake.dtd">
<test>
  <check-me/>
</test>
```

**Comment by C4tWithShell** [comment]
I also found the following error message:
```
ERROR No issues information will be saved as the report file '/home/vshell/sonar-rust/community-rust-plugin/src/test/resources/clippy/invalid-path.txt' can't be read.
 FileNotFoundException: /home/vshell/sonar-rust/community-rust-plugin/src/test/resources/clippy/invalid-path.txt (No such file or directory)
```

There is no file `sonar-rust/community-rust-plugin/src/test/resources/clippy/invalid-path.txt`

**Comment by elegoff** [comment]
This ERROR in log is expected as it comes from a test explicitly checking invalid paths
